#!/usr/bin/python

import csv
import json
from datetime import date

import requests


def get_filename_datetime():
    # Use current date to get a text file name.
    return "file-" + str(date.today()) + ".json"


name = get_filename_datetime()

csvFilePath = 'C:/Users/danie/Desktop/Imports/test.csv'
jsonFilePath = 'C:/Users/danie/Desktop/Imports/JSON/' + name

# Read the CSV and add the data to a dictionary
data = {}
with open(csvFilePath) as csvFile:
    csvReader = csv.DictReader(csvFile)
    for csvRow in csvReader:
        ID = csvRow['ID']
        data[ID] = csvRow

# Write data to a JSON file...
with open(jsonFilePath, "w") as jsonFile:
    jsonFile.write(json.dumps(data, indent=4))

payload = open(jsonFilePath, 'rb')
r = requests.post('https://reqres.in/api/users', data=payload)

print(r.status_code)
